""" Helper functions
" Function to source only if file exists {
" From https://devel.tech/snippets/n/vIIMz8vZ/load-vim-source-files-only-if-they-exist
function! SourceIfExists(file)
  if filereadable(expand(a:file))
    exe 'source' a:file
  endif
endfunction
" }

""" Core functionality
set nocompatible

" Map keys for switching tabs (previous then next)
map <F7> :tabp<CR>
map <F8> :tabn<CR>

" Disable the directional keys
noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>

" Set clipboard behaviour
set clipboard+=unnamedplus

" Vim help settings
set helpheight=30
set helplang=en


""" Look and feel
set ruler
set nu
syntax on
set autoindent

" Size of a hard tabstop
set tabstop=4

" Size of an 'indent'
set shiftwidth=4

" A combination of spaces and tabs are used to simulate tab stops at a width
" other than the (hard) tabstop
set softtabstop=4

" Always uses spaces instead of tab characters
set expandtab

" Draw a verticle line at column 81 to establish a boundary for lines
highlight ColorColumn ctermbg=lightgrey guibg=lightgrey
set colorcolumn=81

" Source fzf
call SourceIfExists("/usr/share/doc/fzf/examples/fzf.vim")
