# General aliases
alias agdu="sudo apt-get update; sudo apt-get dist-upgrade -y; sudo apt autoremove -y;"
alias pip3chk="pip3 list --outdated"
alias pip2chk="pip2 list --outdated"
alias udpip3="pip3 freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs sudo pip3 install -U"
alias udpip2="pip2 freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs sudo pip2 install -U"
